### ISSUE TITLE
init --template

### ISSUE THREAD

**Issue by mosteo** [alire-project/alr#8]
More advanced templates than a bare executable/library

**Comment by Fabien-Chouteau** [comment]
What do you have in mind here?

**Comment by mosteo** [comment]
This was an early idea that instead of/besides the hardcoded `--bin`, `--lib` project skeletons, a "gallery" with more examples could exist, selected by name with this option. The user could also add their own templates for reuse.

That's related to the #11 issue, so users could create these templates simply by providing files with the templates parser syntax.

Many early issues are somewhat vague ideas I wanted to track, more than definite short/mid-term implementation goals. You may close them as you see fit and they can be reopened if they become a realistic proposition later on.

**Comment by Fabien-Chouteau** [comment]
Hi all,

I've started prototyping templated crate support for Alire. Available in the [`template_crate_wip`](https://github.com/alire-project/alire/tree/template_crate_wip) branch, it is based on https://github.com/alire-project/alire/pull/1890 and introduces template release manifests.

A template release differs from a regular release with this field:
```toml
template=true
```

And optional template inputs:
```toml
[template-inputs]
Tmplt_Var1={type="Boolean", default=false}
Tmplt_Var2={type="String", default="str"}
Tmplt_Var3={type="Enum", values=["A", "B"], default="A"}
Tmplt_Var4={type="Integer", default=0}
Tmplt_Var5={type="Integer", first=-1, last=1, default=0}
Tmplt_Var7={type="Real", default=0.0}
Tmplt_Var6={type="Real", first=-1.0, last=1.0, default=0.0}
```
There's an example of template release in the branch.

Using `alr get` to download the template, Alire will ask the user to chose values for the different inputs (or use the mandatory defaults when in non-interactive mode). Alire will then look for any file or folder with the suffix `_tmplt` and translate it using the AWS templates_parser library. File/dir names can be templated as well, using the example above, you can have a `@_LOWER:Tmplt_Var2_@.md_tmplt` file in the template that will be translated to `str.md` (default value).


Ultimately, I think this should be coupled with `alr init`, not `alr get`.
